#ifndef DCS_VERSION_H
#define DCS_VERSION_H

/* Project version. Bumped by hand when shipping a release. Build-time
   metadata (date, git commit, tamper signature) lives in build_info.h
   instead — it's regenerated by the Makefile so this header doesn't need
   to change between commits. (R-15 part 1) */

#define DCS_VERSION_MAJOR 1
#define DCS_VERSION_MINOR 0
#define DCS_VERSION_PATCH 0

#define DCS_STRINGIFY_(x) #x
#define DCS_STRINGIFY(x)  DCS_STRINGIFY_(x)

#define DCS_VERSION_STR  \
    DCS_STRINGIFY(DCS_VERSION_MAJOR) "." \
    DCS_STRINGIFY(DCS_VERSION_MINOR) "." \
    DCS_STRINGIFY(DCS_VERSION_PATCH)

#endif /* DCS_VERSION_H */
