CC     = gcc
CFLAGS = -Wall -Wextra -O2 -std=c99
# MSYS2 workaround: export so gcc subprocess inherits them
export TEMP   = /tmp
export TMP    = /tmp
export TMPDIR = /tmp

# raylib (MSYS2 MinGW64) — only graph_raylib.c includes raylib.h
RAYLIB_INC  = /c/msys64/mingw64/include
RAYLIB_LIB  = /c/msys64/mingw64/lib
RAYLIB_LDFL = -L$(RAYLIB_LIB) -lraylib -lopengl32 -lgdi32 -lwinmm -lm

# ── Phase 2.1 sources ──────────────────────────────────────────────
FW_PLATFORM_SRC = src/framework/platform/platform_windows.c \
                  src/framework/platform/platform_linux.c
FW_PLATFORM_HDR = src/framework/platform/iplatform.h \
                  src/framework/core/oo.h

# ── Phase 2.2 sources ──────────────────────────────────────────────
FW_GRAPH_SRC = src/framework/graphics/graph_raylib.c
FW_GRAPH_HDR = src/framework/graphics/igraph.h \
               src/framework/core/color.h \
               src/framework/core/rect.h

# ── Phase 2.5 app sources ──────────────────────────────────────────
APP_SRC = src/app/circuit_canvas_widget.c \
          src/app/timing_canvas_widget.c \
          src/app/side_toolbar.c \
          src/app/input_panel.c \
          src/app/divider_widget.c \
          src/app/external_view.c \
          src/app/help_dialog.c \
          src/app/command_stack.c \
          src/app/dcs_app.c
APP_HDR = src/app/editor_state.h \
          src/app/circuit_canvas_widget.h \
          src/app/timing_canvas_widget.h \
          src/app/side_toolbar.h \
          src/app/input_panel.h \
          src/app/divider_widget.h \
          src/app/external_view.h \
          src/app/help_dialog.h \
          src/app/command.h \
          src/app/command_stack.h \
          src/app/dcs_app.h

GUI_SRC = src/gui/main.c
GUI_EXE = dcs_gui.exe

# ── R-15 parts 2 + 3: build-time metadata + tamper signature ───────
# src/build_info.c is regenerated on every build (and NOT committed —
# see .gitignore). The cmp-then-mv pattern only touches the file's
# mtime when its content actually changes, so back-to-back builds
# inside the same day at the same commit don't force re-linking.
#
# Tamper signature (R-15 part 3): SHA-256(version|date|commit|salt).
# The salt comes from $DCS_BUILD_SALT (default "dcs-default-salt").
# Runtime startup recomputes the same hash and warns on mismatch.
# This is casual-tamper protection only — the salt is embedded in the
# binary, so an attacker who flips, say, the date can also recompute
# the signature. The check catches accidental binary modification and
# raises the bar for casual fiddling. Real protection needs code signing.
BUILD_INFO_SRC = src/build_info.c
BUILD_INFO_HDR = src/build_info.h src/version.h

# Salt for the tamper signature. Precedence (highest wins):
#   1. make CLI override:    make DCS_BUILD_SALT=my-secret cli
#   2. .env file in cwd:     DCS_BUILD_SALT=... or DCS_BUILD_SALT="..."
#   3. Makefile default:     dcs-default-salt
# Bash inline env-prefix (DCS_BUILD_SALT=x make ...) does NOT work on
# MSYS2 make on Windows — use one of the three above. See .env.example
# for the .env template and threat-model notes.
DCS_BUILD_SALT ?= dcs-default-salt
ifneq (,$(wildcard .env))
    # Pull DCS_BUILD_SALT out of .env, stripping optional surrounding
    # double quotes. `:=` so the value materialises now (before recipes
    # run); make CLI overrides still win because command-line variables
    # outrank Makefile assignments per GNU make precedence rules.
    _ENV_SALT := $(shell grep '^DCS_BUILD_SALT[[:space:]]*=' .env | head -1 | sed -E 's/^DCS_BUILD_SALT[[:space:]]*=[[:space:]]*//; s/^"(.*)"$$/\1/')
    ifneq (,$(_ENV_SALT))
        DCS_BUILD_SALT := $(_ENV_SALT)
    endif
endif
export DCS_BUILD_SALT

# sha256sum is available on MSYS2 (coreutils) and on every Linux distro.
# macOS uses `shasum -a 256`; add a fallback if/when a macOS build matters.
$(BUILD_INFO_SRC): FORCE
	@_d=$$(date +%Y%m%d); \
	 _c=$$(git rev-parse --short=8 HEAD 2>/dev/null || echo unknown); \
	 _salt="$$DCS_BUILD_SALT"; \
	 _ver=$$(grep -E 'DCS_VERSION_(MAJOR|MINOR|PATCH)' src/version.h | grep -oE '[0-9]+' | tr '\n' '.' | sed 's/\.$$//'); \
	 _sig=$$(printf '%s|%s|%s|%s' "$$_ver" "$$_d" "$$_c" "$$_salt" | sha256sum | cut -d' ' -f1); \
	 printf '/* auto-generated by Makefile — do not edit */\n#include "build_info.h"\nconst char *dcs_build_date   = "%s";\nconst char *dcs_build_commit = "%s";\nconst char *dcs_build_salt   = "%s";\nconst char *dcs_build_sig    = "%s";\n' "$$_d" "$$_c" "$$_salt" "$$_sig" > $@.tmp
	@if cmp -s $@.tmp $@ 2>/dev/null; then rm -f $@.tmp; else mv $@.tmp $@; fi

FORCE: ;

# ── R-15 part 3: vendored SHA-256 utility ──────────────────────────
SHA256_SRC = src/sha256.c
SHA256_HDR = src/sha256.h

# ── Phase 2.4 domain sources ───────────────────────────────────────
DOMAIN_SRC = src/domain/gate_and.c \
             src/domain/gate_or.c \
             src/domain/gate_not.c \
             src/domain/gate_nand.c \
             src/domain/gate_nor.c \
             src/domain/gate_xor.c \
             src/domain/gate_xnor.c \
             src/domain/circuit.c \
             src/domain/circuit_io.c \
             src/domain/waveform.c \
             src/domain/simulation.c \
             src/domain/wire_geometry.c
DOMAIN_HDR = src/domain/component.h \
             src/domain/circuit.h \
             src/domain/circuit_io.h \
             src/domain/waveform.h \
             src/domain/simulation.h \
             src/domain/wire_geometry.h

# ── Phase 2.3 sources ──────────────────────────────────────────────
FW_WIDGET_SRC = src/framework/core/focus_manager.c \
                src/framework/core/quit_manager.c \
                src/framework/widgets/frame.c \
                src/framework/widgets/panel.c \
                src/framework/widgets/button.c \
                src/framework/widgets/label.c \
                src/framework/widgets/splitter.c \
                src/framework/widgets/canvas_widget.c \
                src/framework/widgets/menu.c
FW_WIDGET_HDR = src/framework/core/focus_manager.h \
                src/framework/core/quit_manager.h \
                src/framework/core/message.h \
                src/framework/widgets/widget.h \
                src/framework/widgets/frame.h \
                src/framework/widgets/panel.h \
                src/framework/widgets/button.h \
                src/framework/widgets/label.h \
                src/framework/widgets/splitter.h \
                src/framework/widgets/canvas_widget.h \
                src/framework/widgets/menu.h

# ── Phase 2.1: iplatform unit tests ────────────────────────────────
TEST_IPLATFORM_SRC = test/test_iplatform.c
TEST_IPLATFORM_EXE = test/test_iplatform.exe

$(TEST_IPLATFORM_EXE): $(FW_PLATFORM_SRC) $(FW_PLATFORM_HDR) $(TEST_IPLATFORM_SRC)
	$(CC) $(CFLAGS) $(FW_PLATFORM_SRC) $(TEST_IPLATFORM_SRC) -o $@ -lcomdlg32

test_iplatform: $(TEST_IPLATFORM_EXE)
	./$(TEST_IPLATFORM_EXE)

# ── Phase 2.2: igraph offline (vtable / color / layout) tests ──────
TEST_IGRAPH_SRC = test/test_igraph.c
TEST_IGRAPH_EXE = test/test_igraph.exe

$(TEST_IGRAPH_EXE): $(FW_GRAPH_SRC) $(FW_GRAPH_HDR) $(TEST_IGRAPH_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) $(FW_GRAPH_SRC) $(TEST_IGRAPH_SRC) -o $@ $(RAYLIB_LDFL)

test_igraph: $(TEST_IGRAPH_EXE)
	./$(TEST_IGRAPH_EXE)

# ── Phase 2.3 (part 1): widget framework ──────────────────────────
# Offline structural test for widget framework — does not open a window.
TEST_WIDGETS_SRC = test/test_widgets.c
TEST_WIDGETS_EXE = test/test_widgets.exe

$(TEST_WIDGETS_EXE): $(FW_WIDGET_SRC) $(FW_WIDGET_HDR) $(FW_GRAPH_HDR) $(TEST_WIDGETS_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) $(FW_WIDGET_SRC) $(TEST_WIDGETS_SRC) -o $@

test_widgets: $(TEST_WIDGETS_EXE)
	./$(TEST_WIDGETS_EXE)

# Windowed end-to-end demos. Run manually: `make demos` then launch.
DEMO1_SRC = demo/framework_demo.c
DEMO1_EXE = demo/framework_demo.exe
DEMO2_SRC = demo/widget_showcase.c
DEMO2_EXE = demo/widget_showcase.exe

$(DEMO1_EXE): $(FW_PLATFORM_SRC) $(FW_GRAPH_SRC) $(FW_WIDGET_SRC) $(DEMO1_SRC) \
              $(FW_PLATFORM_HDR) $(FW_GRAPH_HDR) $(FW_WIDGET_HDR)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		$(FW_PLATFORM_SRC) $(FW_GRAPH_SRC) $(FW_WIDGET_SRC) $(DEMO1_SRC) \
		-o $@ -lcomdlg32 $(RAYLIB_LDFL)

$(DEMO2_EXE): $(FW_PLATFORM_SRC) $(FW_GRAPH_SRC) $(FW_WIDGET_SRC) $(DEMO2_SRC) \
              $(FW_PLATFORM_HDR) $(FW_GRAPH_HDR) $(FW_WIDGET_HDR)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		$(FW_PLATFORM_SRC) $(FW_GRAPH_SRC) $(FW_WIDGET_SRC) $(DEMO2_SRC) \
		-o $@ -lcomdlg32 $(RAYLIB_LDFL)

demo:  $(DEMO1_EXE)
demos: $(DEMO1_EXE) $(DEMO2_EXE)

# ── Phase 2.4: domain layer + CLI + ported tests ───────────────────
TEST_CIRCUIT_SRC    = test/test_circuit.c
TEST_CIRCUIT_EXE    = test/test_circuit.exe
TEST_CIRCUIT_IO_SRC = test/test_circuit_io.c
TEST_CIRCUIT_IO_EXE = test/test_circuit_io.exe
TEST_CLI_SH         = test/test_cli.sh

$(TEST_CIRCUIT_EXE): $(DOMAIN_SRC) $(DOMAIN_HDR) $(TEST_CIRCUIT_SRC)
	$(CC) $(CFLAGS) $(DOMAIN_SRC) $(TEST_CIRCUIT_SRC) -o $@

test_circuit: $(TEST_CIRCUIT_EXE)
	./$(TEST_CIRCUIT_EXE)

$(TEST_CIRCUIT_IO_EXE): $(DOMAIN_SRC) $(DOMAIN_HDR) $(TEST_CIRCUIT_IO_SRC)
	$(CC) $(CFLAGS) $(DOMAIN_SRC) $(TEST_CIRCUIT_IO_SRC) -o $@

test_circuit_io: $(TEST_CIRCUIT_IO_EXE)
	./$(TEST_CIRCUIT_IO_EXE)

# new dcs_cli built on the new domain layer (still uses iplatform's read_file)
CLI_SRC  = cli/main.c
CLI_EXE  = dcs_cli.exe

$(CLI_EXE): $(FW_PLATFORM_SRC) $(FW_PLATFORM_HDR) $(DOMAIN_SRC) $(DOMAIN_HDR) \
            $(BUILD_INFO_SRC) $(BUILD_INFO_HDR) $(SHA256_SRC) $(SHA256_HDR) $(CLI_SRC)
	$(CC) $(CFLAGS) $(FW_PLATFORM_SRC) $(DOMAIN_SRC) \
		$(BUILD_INFO_SRC) $(SHA256_SRC) $(CLI_SRC) \
		-o $@ -lcomdlg32

cli: $(CLI_EXE)

test_cli: $(CLI_EXE) $(TEST_CLI_SH)
	sh $(TEST_CLI_SH)

# ── Phase 2.5: dcs_gui (app on framework + domain) ─────────────────
$(GUI_EXE): $(FW_PLATFORM_SRC) $(FW_GRAPH_SRC) $(FW_WIDGET_SRC) \
            $(FW_SHAPE_SRC) $(FW_SHAPE_HDR) \
            $(DOMAIN_SRC) $(APP_SRC) $(GUI_SRC) \
            $(BUILD_INFO_SRC) $(BUILD_INFO_HDR) \
            $(SHA256_SRC) $(SHA256_HDR) \
            $(FW_PLATFORM_HDR) $(FW_GRAPH_HDR) $(FW_WIDGET_HDR) \
            $(DOMAIN_HDR) $(APP_HDR)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		$(FW_PLATFORM_SRC) $(FW_GRAPH_SRC) $(FW_WIDGET_SRC) $(FW_SHAPE_SRC) \
		$(DOMAIN_SRC) $(APP_SRC) $(BUILD_INFO_SRC) $(SHA256_SRC) $(GUI_SRC) \
		-o $@ -lcomdlg32 -lm $(RAYLIB_LDFL)

gui: $(GUI_EXE)

# ── Supplement Phase 1: wire_geometry unit tests ───────────────────
TEST_WIRE_GEOMETRY_SRC = test/test_wire_geometry.c
TEST_WIRE_GEOMETRY_EXE = test/test_wire_geometry.exe

$(TEST_WIRE_GEOMETRY_EXE): src/domain/wire_geometry.c src/domain/wire_geometry.h $(TEST_WIRE_GEOMETRY_SRC)
	$(CC) $(CFLAGS) src/domain/wire_geometry.c $(TEST_WIRE_GEOMETRY_SRC) -o $@

test_wire_geometry: $(TEST_WIRE_GEOMETRY_EXE)
	./$(TEST_WIRE_GEOMETRY_EXE)

# ── Supplement Phase 4: canvas-widget mutation-hook integration tests ─
TEST_CCW_SUP_SRC = test/test_circuit_canvas_supplement.c
TEST_CCW_SUP_EXE = test/test_circuit_canvas_supplement.exe

$(TEST_CCW_SUP_EXE): $(FW_WIDGET_SRC) $(FW_WIDGET_HDR) $(FW_GRAPH_HDR) \
                     $(FW_SHAPE_SRC) $(FW_SHAPE_HDR) \
                     $(DOMAIN_SRC) $(DOMAIN_HDR) \
                     src/app/circuit_canvas_widget.c src/app/circuit_canvas_widget.h \
                     src/app/external_view.c src/app/external_view.h \
                     src/app/editor_state.h \
                     $(TEST_CCW_SUP_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		$(FW_WIDGET_SRC) $(FW_SHAPE_SRC) $(DOMAIN_SRC) \
		src/app/circuit_canvas_widget.c src/app/external_view.c \
		$(TEST_CCW_SUP_SRC) -o $@ -lm

test_circuit_canvas_supplement: $(TEST_CCW_SUP_EXE)
	./$(TEST_CCW_SUP_EXE)

# ── R-14 help_dialog widget tests ──────────────────────────────────
TEST_HELP_DIALOG_SRC = test/test_help_dialog.c
TEST_HELP_DIALOG_EXE = test/test_help_dialog.exe

$(TEST_HELP_DIALOG_EXE): $(FW_WIDGET_SRC) $(FW_WIDGET_HDR) $(FW_GRAPH_HDR) \
                         src/app/help_dialog.c src/app/help_dialog.h \
                         $(TEST_HELP_DIALOG_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		src/app/help_dialog.c $(TEST_HELP_DIALOG_SRC) -o $@

test_help_dialog: $(TEST_HELP_DIALOG_EXE)
	./$(TEST_HELP_DIALOG_EXE)

# ── R-15 part 3: SHA-256 unit tests (NIST vectors) ─────────────────
TEST_SHA256_SRC = test/test_sha256.c
TEST_SHA256_EXE = test/test_sha256.exe

$(TEST_SHA256_EXE): $(SHA256_SRC) $(SHA256_HDR) $(TEST_SHA256_SRC)
	$(CC) $(CFLAGS) $(SHA256_SRC) $(TEST_SHA256_SRC) -o $@

test_sha256: $(TEST_SHA256_EXE)
	./$(TEST_SHA256_EXE)

# ── R-5 Stage 9a: command pattern + undo/redo stack ────────────────
TEST_COMMAND_STACK_SRC = test/test_command_stack.c
TEST_COMMAND_STACK_EXE = test/test_command_stack.exe

$(TEST_COMMAND_STACK_EXE): src/app/command.h src/app/command_stack.h \
                          src/app/command_stack.c $(TEST_COMMAND_STACK_SRC)
	$(CC) $(CFLAGS) src/app/command_stack.c $(TEST_COMMAND_STACK_SRC) -o $@

test_command_stack: $(TEST_COMMAND_STACK_EXE)
	./$(TEST_COMMAND_STACK_EXE)

# ── Step 3 Stage 3 (U-5): app-layer test scaffold ──────────────────
TEST_DIVIDER_SRC = test/test_divider_widget.c
TEST_DIVIDER_EXE = test/test_divider_widget.exe

$(TEST_DIVIDER_EXE): $(FW_WIDGET_SRC) $(FW_WIDGET_HDR) $(FW_GRAPH_HDR) \
                    src/app/divider_widget.c src/app/divider_widget.h \
                    $(TEST_DIVIDER_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		src/app/divider_widget.c $(TEST_DIVIDER_SRC) -o $@

test_divider_widget: $(TEST_DIVIDER_EXE)
	./$(TEST_DIVIDER_EXE)

TEST_INPUT_PANEL_SRC = test/test_input_panel.c
TEST_INPUT_PANEL_EXE = test/test_input_panel.exe

$(TEST_INPUT_PANEL_EXE): $(FW_WIDGET_SRC) $(FW_WIDGET_HDR) $(FW_GRAPH_HDR) \
                        $(DOMAIN_SRC) $(DOMAIN_HDR) \
                        src/app/input_panel.c src/app/input_panel.h \
                        $(TEST_INPUT_PANEL_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		$(DOMAIN_SRC) src/app/input_panel.c $(TEST_INPUT_PANEL_SRC) -o $@

test_input_panel: $(TEST_INPUT_PANEL_EXE)
	./$(TEST_INPUT_PANEL_EXE)

TEST_SIDE_TOOLBAR_SRC = test/test_side_toolbar.c
TEST_SIDE_TOOLBAR_EXE = test/test_side_toolbar.exe

# side_toolbar tests instantiate a real circuit_canvas_widget — pull
# in the same APP_SRC + DOMAIN_SRC + FW_WIDGET_SRC mix the canvas
# supplement tests use, minus dcs_app + timing_canvas (not exercised
# here).
$(TEST_SIDE_TOOLBAR_EXE): $(FW_WIDGET_SRC) $(FW_WIDGET_HDR) $(FW_GRAPH_HDR) \
                         $(FW_SHAPE_SRC) $(FW_SHAPE_HDR) \
                         $(DOMAIN_SRC) $(DOMAIN_HDR) \
                         src/app/circuit_canvas_widget.c src/app/circuit_canvas_widget.h \
                         src/app/side_toolbar.c src/app/side_toolbar.h \
                         src/app/external_view.c src/app/external_view.h \
                         src/app/editor_state.h \
                         $(TEST_SIDE_TOOLBAR_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		$(FW_SHAPE_SRC) $(DOMAIN_SRC) src/app/circuit_canvas_widget.c \
		src/app/side_toolbar.c src/app/external_view.c \
		$(TEST_SIDE_TOOLBAR_SRC) -o $@ -lm

test_side_toolbar: $(TEST_SIDE_TOOLBAR_EXE)
	./$(TEST_SIDE_TOOLBAR_EXE)

# ── Step 3 Stage 6 (U-21 part A): shape DSL ────────────────────────
FW_SHAPE_SRC = src/framework/shape.c
FW_SHAPE_HDR = src/framework/shape.h

TEST_SHAPE_SRC = test/test_shape.c
TEST_SHAPE_EXE = test/test_shape.exe

$(TEST_SHAPE_EXE): $(FW_SHAPE_SRC) $(FW_SHAPE_HDR) $(FW_GRAPH_HDR) $(TEST_SHAPE_SRC)
	$(CC) $(CFLAGS) $(FW_SHAPE_SRC) $(TEST_SHAPE_SRC) -o $@ -lm

test_shape: $(TEST_SHAPE_EXE)
	./$(TEST_SHAPE_EXE)

TEST_DCS_APP_SRC = test/test_dcs_app.c
TEST_DCS_APP_EXE = test/test_dcs_app.exe

# dcs_app's init wires up the whole app — needs every framework +
# domain + app source, same as the GUI build. Pull in everything
# except the raylib backend (we use a stub igraph in the test).
$(TEST_DCS_APP_EXE): $(FW_PLATFORM_SRC) $(FW_GRAPH_HDR) $(FW_PLATFORM_HDR) \
                    $(FW_WIDGET_SRC) $(FW_WIDGET_HDR) \
                    $(FW_SHAPE_SRC) $(FW_SHAPE_HDR) \
                    $(DOMAIN_SRC) $(DOMAIN_HDR) $(APP_SRC) $(APP_HDR) \
                    $(BUILD_INFO_SRC) $(BUILD_INFO_HDR) \
                    $(SHA256_SRC) $(SHA256_HDR) \
                    $(TEST_DCS_APP_SRC)
	$(CC) $(CFLAGS) -I $(RAYLIB_INC) \
		$(FW_PLATFORM_SRC) $(FW_WIDGET_SRC) $(FW_SHAPE_SRC) \
		$(DOMAIN_SRC) $(APP_SRC) $(BUILD_INFO_SRC) $(SHA256_SRC) \
		$(TEST_DCS_APP_SRC) -o $@ -lcomdlg32 -lm

test_dcs_app: $(TEST_DCS_APP_EXE)
	./$(TEST_DCS_APP_EXE)

# ── future phases (2.6 layout block, ...) ──────────────────────────

.PHONY: test test_iplatform test_igraph test_widgets test_circuit test_circuit_io test_cli test_wire_geometry test_circuit_canvas_supplement test_help_dialog test_sha256 test_command_stack test_divider_widget test_input_panel test_side_toolbar test_dcs_app test_shape cli gui demo demos clean

test: test_iplatform test_igraph test_widgets test_circuit test_circuit_io test_cli test_wire_geometry test_circuit_canvas_supplement test_help_dialog test_sha256 test_command_stack test_divider_widget test_input_panel test_side_toolbar test_dcs_app test_shape

clean:
	rm -f test/*.exe test/*.o demo/*.exe $(CLI_EXE) $(GUI_EXE)
